services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ilyass
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - database
    volumes:
      - ./backend:/app
    entrypoint: /app/entrypoint.sh
    networks:
      - app-network

  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ilyass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
