# Generated by Django 4.2.11 on 2024-11-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_client_ice_alter_client_pays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
    ]
